import { HumanMessage } from "@langchain/core/messages";
import { StateSchema, MessagesValue, StateGraph, START, END, ReducedValue } 
from "@langchain/langgraph";
import { mistralModel,cohereModel,geminiModel } from "./models.ai.js";
import {createAgent,providerStrategy} from "langchain" ;
import type { GraphNode } from "@langchain/langgraph";
import { compile } from "tailwindcss";
import {promise, z} from "zod"
import { MistralAI } from "@langchain/mistralai";
import type { TypeOf } from "zod/v3";

// nodes share data with each other and the format of that data is define in this stateSchema

const state = new StateSchema({
  problem:z.string().default(""),
  solution_1:z.string().default(""),
  solution_2:z.string().default(""),
  judge:z.object({
    solution_1_score:z.number().default(0),
    solution_2_score:z.number().default(0),
    solution_1_reasoning:z.string().default(""),
    solution_2_reasoning:z.string().default(""),
  })
})

// here both AI model get the problem from user and generate the solution.
const solutionNode : GraphNode<typeof state> = async (state) => {
  const [mistralResponse,cohereResponse] = await Promise.all([
    mistralModel.invoke(state.problem),
    cohereModel.invoke(state.problem),
  ])

  return{
    solution_1:mistralResponse.text,
    solution_2:cohereResponse.text,
  }
}

// here judge compare both solution and evaluate the score for both solutions.
const judgeNode:GraphNode<typeof state > = async (state) => {
  const {problem,solution_1,solution_2} = state

  const judge = createAgent({
    model:geminiModel,
    responseFormat:providerStrategy(z.object({
      solution_1_score:z.number().min(0).max(10),
      solution_2_score:z.number().min(0).max(10),
      solution_1_reasoning:z.string(),
      solution_2_reasoning:z.string(),
    })),
      systemPrompt:`You are judge tasked with evaluating two solutions generated by different AI models. please provide a score out of 10 for each solution, along with your reasoning for the scores.`
  })

  const judgeResponse = await judge.invoke({
    messages:[
      new HumanMessage(`
        problem:${problem}
        solution_1:${solution_1}
        solution_2:${solution_2}
        please evaluate the solutions and provide the scores and reasoning.
        `)
    ]
  })

  // judgeResponse in structuredFormat
  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
  } = judgeResponse.structuredResponse

  return{
    judge:{
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
    }
  }
}

// StateGraph for creating edges and nodes to define the flow of nodes connections , how the data will flow.

const graph = new StateGraph(state)
      .addNode("solution",solutionNode)
      .addNode("judge",judgeNode)
      .addEdge(START,"solution")
      .addEdge("solution","judge")
      .addEdge("judge",END)
      .compile()

export default async function runGraph(problem:string) {
  const result = await graph.invoke({
    problem:problem
  })

  return result
}