import { StateGraph, StateSchema, START, END, type GraphNode, type CompiledStateGraph} 
from "@langchain/langgraph";
import { mistralModel,geminiModel,cohereModel } from "./models.ai.js";
import {createAgent,providerStrategy,HumanMessage} from "langchain" ;
import { z} from "zod"


// nodes share data with each other and the format of that data is define in this stateSchema

const state = new StateSchema({
  problem:z.string().default(""),
  solution_1:z.string().default(""),
  solution_2:z.string().default(""),
  judge:z.object({
    solution_1_score:z.number().default(0),
    solution_2_score:z.number().default(0),
    solution_1_reasoning:z.string().default(""),
    solution_2_reasoning:z.string().default(""),
  })
})

// here both AI model get the problem from user and generate the solution.
const solutionNode : GraphNode<typeof state> = async (state) => {
  console.log("Solution node start");
  const [mistralResponse,cohereResponse] = await Promise.all([
    mistralModel.invoke(state.problem),
    cohereModel.invoke(state.problem),
  ])
  console.log("Solution node done");

  return{
    solution_1:mistralResponse.text,
    solution_2:cohereResponse.text,
  }
}

// here judge compare both solution and evaluate the score for both solutions.
const judgeNode:GraphNode<typeof state > = async (state) => {
  const {problem,solution_1,solution_2} = state

  const judge = createAgent({
    model:geminiModel,
    responseFormat:providerStrategy(z.object({
      solution_1_score:z.number().min(0).max(10),
      solution_2_score:z.number().min(0).max(10),
      solution_1_reasoning:z.string(),
      solution_2_reasoning:z.string(),
    })),
      systemPrompt:`You are judge tasked with evaluating two solutions generated by different AI models. please provide a score out of 10 for each solution, along with your reasoning for the scores.`
  })

  const judgeResponse = await judge.invoke({
    messages:[
      new HumanMessage(`
        problem:${problem}
        solution_1:${solution_1}
        solution_2:${solution_2}
        please evaluate the solutions and provide the scores and reasoning.
        `)
    ]
  })

  // judgeResponse in structuredFormat
  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
  } = judgeResponse.structuredResponse

  return{
    judge:{
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
    }
  }
}

// StateGraph for creating edges and nodes to define the flow of nodes connections , how the data will flow.

const graph = new StateGraph(state)
      .addNode("solution",solutionNode)
      .addNode("judge_node",judgeNode)
      .addEdge(START,"solution")
      .addEdge("solution","judge_node")
      .addEdge("judge_node",END)
      .compile()

export default async function runGraph(problem:string) {
  console.log("Judge node start");
  const result = await graph.invoke({
    problem:problem
  })
  console.log("Judge node done");

  return result
}